name: Deploy Assets to Minio
on:
  push:
    branches:
      - master
jobs:
  deploy-to-minio:
    runs-on: ubuntu-latest
    steps:
      - name: Install Minio Client
        run: |
          curl -LO https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/
      - name: Set Minio Alias
        run: |
          mc alias set minio http://192.168.4.129:9000 aGhrfpvoYjBpMipmh4J0 qOJ5NcKW1nu6VeFyZhP6AGvS9cAz4jItzUORhoS4
      - name: Test list directory
        run: |
          cd ../.. && pwd && ls -la
      - name: Upload src Directory to Minio Bucket
        run: |
          mc cp --recursive ~/src/ minio/jbunkerhill.com/